[package]
name = "deno"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = "0.126.0"
v8 = "0.41.0"
serde_v8 = "0.39.0"
serde_json = "1.0.79"
tokio = { version = "1.17.0", features = ["full"] }