name: build-libdeno

on:
  push:
    branches:    
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo crates
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        path: |
                ~/.cargo
                android-ndk*
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: install aarch64 target
      run: |
        rustup target add aarch64-linux-android
    - name: Build libdeno
      run: |
              ./build.sh
      #RUSTFLAGS="-L `pwd`/deps -L /home/jonas/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/30" RUST_BACKTRACE=1 cargo  build --target=aarch64-linux-android
